version: '2.1'
services:
  prom-conf:
    image: infinityworks/prom-conf:17
    volumes:
      - /etc/prom-conf/

  alertmanager:
    image: prom/alertmanager
    stdin_open: true
    volumes:
      - /etc/alertmanager
    tty: true
    ports:
      - 9093:9093/tcp
    command:
      - -config.file=/etc/alertmanager/config.yml
  
  prometheus:
    tty: true
    image: prom/prometheus:v1.5.2
    command: -alertmanager.url=http://alertmanager:9093 -config.file=/etc/prom-conf/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles
    ports:
      - 9090:9090
    volumes_from:
       - prom-conf

  graf-db:
    tty: true
    image: infinityworks/graf-db:10
    command: cat
    volumes:
      - /var/lib/grafana/

  grafana:
    tty: true
    image: grafana/grafana:4.2.0
    ports:
      - 3000:3000
    volumes_from:
      - graf-db
    volumes:
      - /etc/grafana/
    links:
      - prometheus:prometheus